### ISSUE TITLE
Floating windows should not be rendered with transparent background

### ISSUE THREAD

**Issue by nicolas-yangli** [yatli/fvim#154]
![floating-window](https://user-images.githubusercontent.com/4900149/89276012-a8d0df00-d675-11ea-810a-f59eb0182cfa.png)

**Comment by yatli** [comment]
Got it. Thanks!

**Comment by yatli** [comment]
I think this will only trigger if the pum background is same as the default the background, and the theming code always gives a transparent bg for default...

**Comment by yatli** [comment]
Should be fixed now.

**Comment by nicolas-yangli** [comment]
![图片](https://user-images.githubusercontent.com/4900149/89651731-ee500f00-d8f6-11ea-83ef-9015a995f772.png)

I think it is still not working as expected.

**Comment by yatli** [comment]
@nicolas-yangli are you building off the latest HEAD?

**Comment by nicolas-yangli** [comment]
I downloaded artifacts from azure pipelines.

**Comment by yatli** [comment]
@nicolas-yangli just another attempt to fix this problem. Feel free to try out.
