### ISSUE TITLE
Unable to Update Arch User Repo Pkgbuild to v0.2.392+g646a86f

### ISSUE THREAD

**Issue by jjohnson338** [yatli/fvim#191]
I've attempted to update the AUR package build to the latest version, but I'm running into a couple issues. Firstly, the solution now contains two projects, so we have to specify a project. I've assumed `fvim.fsproj` is the appropriate target here. Is that correct?

After making that change, I'm hitting a build error that stops compilation:
![image](https://user-images.githubusercontent.com/1017310/126869511-2536720e-7888-4fa8-a89e-5ea294800122.png)

I likely won't have time over the next little bit to update the package, so I'm also attaching my WIP on the update in-case it's helpful to you for updating the AUR package:
```
diff --git a/.SRCINFO b/.SRCINFO
index a6111f8..dd16727 100644
--- a/.SRCINFO
+++ b/.SRCINFO
@@ -1,6 +1,6 @@
 pkgbase = fvim
 	pkgdesc = Cross platform Neovim front-end UI, built with F# + Avalonia
-	pkgver = 0.2.349_9f6430d
+	pkgver = 0.2.392_g646a86f
 	pkgrel = 1
 	url = https://github.com/yatli/fvim
 	arch = x86_64
@@ -12,8 +12,7 @@ pkgbase = fvim
 	provides = fvim
 	conflicts = fvim
 	options = staticlibs
-	source = https://github.com/yatli/fvim/archive/v0.2.349+9f6430d.tar.gz
+	source = https://github.com/yatli/fvim/archive/refs/tags/v0.2.392+g646a86f.tar.gz
 	md5sums = SKIP
 
 pkgname = fvim
-
diff --git a/PKGBUILD b/PKGBUILD
index 736a804..44336e7 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -1,6 +1,6 @@
 # Maintainer: Jared Johnson <jaredj@gmx.com>
 pkgname=fvim
-pkgver=0.2.349_9f6430d
+pkgver=0.2.392_g646a86f
 _pkgver=$(echo "${pkgver}" | sed -e "s/_/-/g")
 pkgrel=1
 pkgdesc="Cross platform Neovim front-end UI, built with F# + Avalonia"
@@ -13,13 +13,13 @@ makedepends=('dotnet-host' 'dotnet-sdk-3.1')
 optdepends=()
 provides=('fvim')
 conflicts=('fvim')
-source=("https://github.com/yatli/fvim/archive/v0.2.349+9f6430d.tar.gz")
+source=("https://github.com/yatli/fvim/archive/refs/tags/v0.2.392+g646a86f.tar.gz")
 md5sums=('SKIP')
 options=('staticlibs')
 
 build() {
     cd "${srcdir}/${pkgname}-${_pkgver}"
-    dotnet publish \
+    dotnet publish fvim.fsproj \
         -f netcoreapp3.1 \
         -c Release \
         -r linux-x64 \
```

**Comment by yatli** [comment]
thanks @jjohnson338 ! I also received aur email today. Will deal with this shortly.

**Comment by yatli** [comment]
I've applied your patch and it builds fine on my side 😱

**Comment by yatli** [comment]
also builds fine in the chroot environment (`aur sync -c fvim`)

**Comment by yatli** [comment]
@jjohnson338 could you please verify? I've pushed to aur but I'm not sure if that's the right move... me arch noob (

**Comment by jjohnson338** [comment]
Hi @yatli, I nuked my `fvim` install and tried to pull down the latest package from the aur. I am still getting the same build error. I took a look at references to that file in the `fvim` repo and it appears the `fvim.fsproj` reference to it is missing the parent dir. Maybe this builds on other platform?

After updating that path, it's building fine on my machine. I've created a PR to update that [here](https://github.com/yatli/fvim/pull/192).

Please take a look when you get a chance.
