### ISSUE TITLE
Keyboard layouts are ignored (all platforms)

### ISSUE THREAD

**Issue by cknoerle** [yatli/fvim#36]
fvim 0.2 and also previous version do not handle my standard German keyboard layout correctly.
For example a ":" is not on "SHIFT-." but on "SHIFT-ü"

AFAIR this also happened to me in previous builds of fvim.

Windows 1809 build 17763.615 settings:
- Region: Germany
- Regional format: German (Germany)
- Windows display language: English (United States)

Let me know what else you need.
Thanks in advance!

**Comment by yatli** [comment]
This might be an upstream Avalonia bug.
I also notice some problems for Mac keyboards -- for a Japanese layout keyboard with different arrangement of symbols -- but fvim treats the keystrokes as if it's on a standard US keyboard (yeah, got shift+"something" for ':', but on the actual keyboard it's somewhere else)

Does this match the problem you're encountering?
I can file another issue to the upstream (or like the last time, send a PR over).

**Comment by cknoerle** [comment]
Yes, sounds exactly like my problem.
I already had the feeling it was standard US layout for some but not all the keys.


Am 23.07.2019 um 08:57 schrieb Yatao Li <notifications@github.com>:

This might be an upstream Avalonia bug.
I also notice some problems for Mac keyboards -- for a Japanese layout keyboard with different arrangement of symbols -- but fvim treats the keystrokes as if it's on a standard US keyboard (yeah, got shift+"something" for ':', but on the actual keyboard it's somewhere else)

Does this match the problem you're encountering?
I can file another issue to the upstream (or like the last time, send a PR over).

**Comment by yatli** [comment]
Alright. Let me make another attempt at the Avalonia key mapping problem.
I'll let you know when I make progress on this.

**Comment by yatli** [comment]
The issue is reproduced on my end.

OS: Windows 10 1903
FVim: HEAD
Locale: English(United States)
Language: Deutsch(Deutschland)
Language pack is not installed, just basic typing.
Physical keyboard: QWERTY standard 104 key

Open up `notepad.exe`, type `[;'`
Got result: `üöä`

From the above result, I figure it'd a QWERTZ layout.

Open up `FVim.exe`, type `[;'`
Got result: `;``'`

Which is a bit puzzling -- it's neither QWERTY, nor the German QWERTZ.
`y` and `z` are swapped indeed.

**Comment by Thanood** [comment]
Hi @yatli 
First of all, thanks for creating a neovim ui on the .Net platform. 😃 

I'm experiencing the same issue.
I've had a little dive into your code and traces while I've tried fvim key commands and I may be able to at least give some pointers.

Please take the following with a grain of salt since I'm neither an F# expert nor an Avalonia expert.

I'm using a German keyboard layout where ":" is on "SHIFT-." (so, SHIFT-period). The triggered input is ">".
When typing this key combination, "SHIFT-period" is exactly what is logged:

```
model: grid #1: OnInput: Key (Shift,OemPeriod)
```

So keystroke detection seems to work, right?
I've found that trace here: https://github.com/yatli/fvim/blob/master/model.fs#L398 so I attached a breakpoint.

The pressed key combination is then transformed here: https://github.com/yatli/fvim/blob/master/model.fs#L410

which seems to trigger the match here: https://github.com/yatli/fvim/blob/master/model.fs#L205
(sorry for all the links 😉 )

"SHIFT-period" is then explicitly transformed to nvim_input ">" here: https://github.com/yatli/fvim/blob/master/model.fs#L299

Of course, changing

```
        |  Key(HasFlag(KeyModifiers.Shift), Key.OemPeriod)            -> Normal ">"
```
to
```
        |  Key(HasFlag(KeyModifiers.Shift), Key.OemPeriod)            -> Normal ":"
```

"solves" the issue (for users of a German keyboard layout, therefore the air quotes 😃).

**Comment by fc1943s** [comment]
+1
Having the same problem with the ABNT2 layout.

Is this something that must be implemented by hand or the layout translation should be handled by the OS itself?

**Comment by krissen** [comment]
+1
Same problem. MacOS. Feels like the keys which are actually entered correspond to the standard US layout, as has been noted above. I'm using a Swedish keyboard layout.

**Comment by jonoll123** [comment]
Same problem for me as well, Windows 10 using a Swedish keyboard. The resulting key presses appear to be neither Swedish nor US. If I switch to US layout in Windows it works as expected, but I would rather use the Swedish layout...

**Comment by sphynx79** [comment]
Same problem for me Windows 10 using a Italian keyboard layout, but fvim use English layout.

**Comment by yatli** [comment]
I've done another round of research on this.

Windows: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexa
macOS: https://stackoverflow.com/questions/18408565/map-nsevent-keycode-to-virtual-key-code#:~:text=To%20translate%20from%20the%20virtual,kTISPropertyUnicodeKeyLayoutData%20as%20the%20property%20key.
Linux: https://tronche.com/gui/x/xlib/input/keyboard-encoding.html

As the number of users with this problem increases I'd start to feel guilty for pushing this one back for other stuff..

A question for you guys, how do you expect the vim key mapping to behavior? For example if I want to go INSERT, should I press "i", or whatever key located at where the en-US "i" is?

**Comment by yatli** [comment]
I've done another round of research on this.

Windows: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeyexa
macOS: https://stackoverflow.com/questions/18408565/map-nsevent-keycode-to-virtual-key-code#:~:text=To%20translate%20from%20the%20virtual,kTISPropertyUnicodeKeyLayoutData%20as%20the%20property%20key.
Linux: https://tronche.com/gui/x/xlib/input/keyboard-encoding.html

As the number of users with this problem increases I'd start to feel guilty for pushing this one back for other stuff..

A question for you guys, how do you expect the vim key mapping to behavior? For example if I want to go INSERT, should I press "i", or whatever key located at where the en-US "i" is?

**Comment by yatli** [comment]
Change of plan -- instead of solving this upstream I'll see if I can do it from fvim directly and then ask them to backport.

**Comment by krissen** [comment]
@yatli My two cents, in short: keys should be mapped according to the system settings, not according to en-US. 

Longer version: (`i` would probably be mapped at the same key in most keyboard layouts. `:` is an example that has been mentioned above, which is mapped differently on different keyboard layouts.) On a keyboard which is set by system to Swedish, I currently have to press `ö` in fvim to get a `:`. When in fact I would expect to get a `:` when I press what, in Swedish keyboards, is mapped to `:`. That is, following the system keyboard settings.

**Comment by yatli** [comment]
understood.

**Comment by yatli** [comment]
@krissen any comments on symbol processing? Like, is there any symbol that doesn't exist on the en-US keyboard?

**Comment by krissen** [comment]
@yatli There are. Just speaking from my own workflow/vim-config, those symbols would not be important with regards to commands and such (seldom used in binds), but naturally are essential for writing text. That is, I could not use an editor which would not be able to input symbols such as `åäö'. Other keyboard layouts would have other symbols, particular to their languages. I believe there has been german examples earlier in this issue-thread. 

The key thing (pun intended) really is, for a key-press to be predictable. That is, for key-presses in one app to be the same in every other: that which is set by the system.

**Comment by yatli** [comment]
> åäö

Ah, I mean punctuations. :)

**Comment by krissen** [comment]
Oh, I see. Nonesuch that I am aware of.

**Comment by yatli** [comment]
There's a problem wrt punct rewriting.
According to https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeya :

> MAPVK_VK_TO_CHAR 2 | uCode is a virtual-key code and is translated into an unshifted character value in the low-order word of the return value. Dead keys (diacritics) are indicated by setting the top bit of the return value. If there is no translation, the function returns 0.

This is the only entry to translate the key codes into mapped keys -- but it translates into unshifted keys.
I don't understand how can I go from unshifted to a shifted character here... Thoughts?

**Comment by yatli** [comment]
hmm. this may help: https://stackoverflow.com/questions/5825820/how-to-capture-the-character-on-different-locale-keyboards-in-wpf-c

**Comment by yatli** [comment]
Ok PR is up: https://github.com/AvaloniaUI/Avalonia/pull/4447

**Comment by yatli** [comment]
@krissen another question :)

Suppose you're in a terminal. What happens if you press Ctrl+å? Is there some kind of control sequence, or escape sequence?

**Comment by krissen** [comment]
Sure thing! In a terminal, `ctrl-å` results in `^]`.

**Comment by yatli** [comment]
Ooh that's interesting. I didn't expect that 0.0
Then how do you type a plain ']'?

I'm trying SWE on a en-US 87key. Haven't figured that out.

**Comment by krissen** [comment]
I'm on macOS and type `option-9` for `]`. `shift+option-9` for `}`. Same modifiers but `8` for `[` and `{`. (Differs a bit from windows/linux.)

**Comment by yatli** [comment]
I see. I was also guessing alt-gr because it's not on my keyboard. It's definitely more sophisticated than I thought!

**Comment by graphixillusion** [comment]
I have the exact same problem: nvim works, fvim doesn't recognize my IT layout.

**Comment by Martin-Nyaga** [comment]
+1. I have a UK layout for my keyboard, but FVim seems to be stuck on US keys. So for example, " is swapped with @.

**Comment by gibboni** [comment]
Hi @yatli! Any news on the progress of this? I've been wanting to test fvim properly, but this issue prevents that. I use FI layout on both Win10 and Linux.

**Comment by Swonkie** [comment]
Same issue here. I just want to emphasize that this is a serious issue. Since I can't enter `:` the program is unusable for me. I don't want to learn the US keyboard layout on top of learning vim. So I'm uninstalling fvim for now - might come back later when this is fixed.

**Comment by JSchrtke** [comment]
Any news on this? I just wanted to try FVim, and it does look really good at first sight, but this issue makes in unsuable for me. It's a bit frustrating this is taking so long to fix.

**Comment by yatli** [comment]
FYI it's not likely the PR will get in soon: https://github.com/AvaloniaUI/Avalonia/pull/4447

So maybe we should improvise a bit... I just need some ideas how other frontends deal with keyboard mappings.
Maybe mix-and-match keyboard events with text input events.
But that could also bring in new issues.
I need to know a clean way of doing this before actually implementing it.
Thoughts?

**Comment by JSchrtke** [comment]
I unfortunately have nothing technical to contribute, since I don't know F#, nor about other neovim frontends.
But I agree this definitely needs a fix, or atleast a workaround, asap, as there is basically no way to use this proper if you're not used to a US keyboard layout. And that is a shame, because I'm itching to try FVim.

**Comment by yatli** [comment]
Please let me know if you guys want to talk in a live session, to teach me how a non-US keyboard layout really works in vim.
I need your input to support the workaround.

**Comment by krissen** [comment]
Thank you for the offer, yatli. However, I think you should rather pursue a general way of making sure that FVim is interacting with the "system keyboard", i.e. the layout set by the operating system, rather than either assuming a layout or interacting with some kind of "hardware layout" or some such. Although I have no knowledge of F# whatsoever, surely there must be a way to catch keys "as interpreted by the operating system"?

The issue isn't how a non-US keyboard layout works in ViM, but rather that keys are mapped differently in different languages. What we want is for FVim to get, that when I press, say, "shift + the second hardware key from the right-hand shift-key", it is mapped to ":". Whereas you would, on a US-keyboard, press a different hardware key for the same result (":"). 

It wouldn't help, I think, if we'd sit down and show you what it looks like, or how ViM behaves on non-US keyboards. ViM works the same way on all keyboards --- but different layouts have different hardware keys mapped to, say, ":". You need to catch pressed keys in the same manner as the OS does, not have FVim make an interpretation separate from the OS.

**Comment by yatli** [comment]
Thank you for the explanation @krissen !
And yeah.. That's the part I can't get my thinking through. Say every key has a virtual code, no matter what layout it is. Let's call it VK. Generally, I'd like the OS to provide the translation service to me, so I ask for `F = get_translation(layout)`, and, VK in, F(VK) out. Simple, right.

But getting modifiers involved fries my brain. Say there is a key that `F(VK)=TR` where TR is translated text, and CTRL is pressed. The way Neo/Vim process CTRL+key is that you send a string "<C-TR>" (C for control). But think about when TR=å, and we send through "<C-å>" -- how is that going to be understood as "<C-[>"?

**Comment by krissen** [comment]
I'd say you're still trying to figure it out the hard way --- but, entirely unfamiliar with Avalonia, perhaps that is the path you have to take.

Just to reiterate the point in my post above, using your recent example. It shouldn't matter what hardware keys are actually pressed, what matters is what the system interprets it as. You shouldn't, I'd think, have to bother yourself with how the user has his or her keys mapped, but what input the system tells you it has received. You shouldn't have to tackle all the different hardware keyboards and keyboard layouts there is. That is already tasked to the OS. 

Never mind if the user _presses_ hardware keys `<C-å>` or `<C-[>`, what matters is what it _means._ That interpretation is tasked to the OS, not to the individual applications (unless said applications are made with programming languages close to the hardware, not interfacing with the operating system). Hardware makes signal "keys `<Ctrl-Alt-8>` pressed" (yes, those are the keys I'd press on macOS, if I'd want `<CTRL+[>`); the OS interprets it: "ah, I see you want to express `<C-[>`" and forwards it; the listening application reads signal "input `<C-[>` received" and does what the user expects when said input is received.

I would think you'd be able to interface with the OS and from there receive the signal `<C-[>`. But perhaps Avalonia isn't there yet? Neither in the core or additional libraries? I don't know. Looking at some of the linked bug reports/feature requests, it looks like it might not be. It surprises me, but what do I know. 🤷‍♂️

**Comment by yatli** [comment]
Good timing. I'm staring at your comment for like 20 minutes :D

**Comment by yatli** [comment]
In a Neovim paradise, the OS just sends`<C-[>` and I would have nothing to complain about!
But in reality (read: Avalonia) that's not likely to happen.

In Avalonia there are two kinds of keyboard events -- text input events and key press events.
Normally a programmer will just work with "text input", which is already layout-translated (at least for Windows).
But here we're trying to forward everything that happens to the keyboard to Neovim -- and text input is not enough -- it doesn't even have the concept of modifier keys.
So what we get here is tuples of `Modifiers * KeyCode` where `KeyCode` is a layout-agnostic number (VK in my example) -- or rather say, "what key it should be if it's en-US".

Because Avalonia doesn't know about layouts, there's no way that the message will be translated, with keycode, or even the modifiers, being translated.
What's worse, the key codes we're looking at isn't OS-specific keys but normalized by Avalonia, so we cannot directly go back to an OS service.

So what you're asking is a good end result (Neovim paradise!) but there's a long way to go...

**Comment by krissen** [comment]
I guess Avalonia must have other great features going for it, but this sounds like an "early beta" type of issue. We're not talking about a Neovim paradise in my opinion, but merely basic functionality of a programming language; to be able to read input as it is intended. That is not Neovim specific. In _any_ application I'd input text in, I would expect to be able to write åäö, find characters like ]≈± where I'd expect them and so on. So, if I'd consider developing an application, I know for sure I won't choose Avalonia. 😂

My two cents: you should not beat your head against this particular wall. It sounds like it is Avalonia's issue. I'd advise you not to try and emulate all possible alternatives of keyboards and keyboard mappings; it would simply be too much work.

Possibly: leave the bug report open, and write a clear message in the README (referencing the issue here and in Avalonia's issue tracker): as long as Avalonia can't interpret the keyboard settings of the OS, FVim can only support standard US keyboards. Once this is fixed in Avalonia, things ought automagically work in FVim as well.

It's either that or ditch Avalonia. And as I'm guessing the latter wouldn't be an option, just keep doing what you like, and refer us non-US keyboard users to Avalonias bug tracker! It is their feature to add / bug to fix, not yours, by the sound of it.

**Comment by yatli** [comment]
Good point. I've updated the README to point to this issue, thanks!
I chose Avalonia because it's actually the best cross-platform UI framework for .NET, imo. It's like cutting through the hyperplane -- Choose wpf/uwp? No cross-platform. Choose Avalonia? Rough edges. Choose lower-level stuff like Skia/SDL/you-name-it? No advanced UI layouts and OS services. :)
Avalonia is moving forward so I take it the best of the three options above.
I will continuously work with them to see what's the best way to incorporate the layouts.

**Comment by JSchrtke** [comment]
Your choice makes sense, cross-platform is always kind of a headache. I'm definitely surprised this is issue exists in Avalonia though, seems like a huge oversight to me.
But I agree, while FVim needs to have this fixed, it doesn't make sense to fix it here, when Avalonia is the real issue.

You did already send them a pull request with a potential fix though, what is preventing that from being merged?

**Comment by krissen** [comment]
The following does not add to the issue at hand, but if you're curious how the keyboard layouts look like, @yatli, [this](http://www.farah.cl/Keyboardery/A-Visual-Comparison-of-Different-National-Layouts/#sv) website gives a good visual representations of many keyboard layouts, as compared to en-US. (Link goes directly to the Swedish/Finnish one.) Do note that this is only for Windows/Linux; macOS differs, but only in details (like no `alt-gr`, the addition of `⌘` and slightly different placement/usage of some symbols, such as `[, ], {, }` for example.)

**Comment by yatli** [comment]
@JSchrtke it's a breaking change to their existing events so I totally understand their decision.
Need to work out a non-intrusive way....

**Comment by dartacao** [comment]
How's the status on this change? Pretty much the only thing stopping me from using this as a main GUI now...

**Comment by JSchrtke** [comment]
Is this still being worked on?

**Comment by yatli** [comment]
Update: some new findings.
The event system works like this:

- On each key stroke, a `KeyDown` event is produced
- If it decodes to something that's plausible for a GUI Textbox control (readable text), a `TextInput` event is produced, following `KeyDown`
- TextInput appears to respect keyboard mappings.
  - However, not all `KeyDown` are paired with a `TextInput`, and that makes sense -- if you press down Shift, a KeyDown is sent, but that does not add text to an input field unless you do something else together with it
  - Another example, if you press Ctrl-Q, no text, correct?
  - Problem here: we fall back to `KeyDown`, and we don't know what are the mapped values.

Really, that's the part I don't understand. The standard vim key mappings have both keys with/without modifiers.
How do people with non-enUS mappings use the vim mappings? Like, if I want to enter BLOCK-VISUAL, I press `<c-v>`, but in another layout like `dvorak`, which one of the following is true:
- Unmapped: send `<c-v>` to neovim when raw key sequence `<c-x>` is pressed
- Mapped: send `<c-v>` to neovim when raw key seqeuence `<c-.>` is pressed
?

**Comment by krissen** [comment]
Your question seems to conflate "non-enUS" mappings with dvorak, so not 100% how to answer (although I don't use en-US, I don't use dvorak either but qwerty).

But, for what it's worth, I press `<c-v>` to enter `BLOCK-VISUAL` with all the different mappings I use (Swedish, Finnish, English (en-GB)).

**Comment by yatli** [comment]
> Your question seems to conflate "non-enUS" mappings with dvorak

Replace `dvorak` with `AZERTY` and try `<c-q>`, what's different?

**Comment by krissen** [comment]
I don't know? Sorry, not sure what you're asking about here.

**Comment by bybor** [comment]
I hope below helps to @yatli, so he may confirm if this is what he asks about.

This is probably off-topic, LMK if I should delete it from here (or just delete it ), it's fine with me.

`fvim` doesn't allow you to switch layouts, it ignores whatever you do. It's what this issue is about.

---

I'm on Windows, I'll describe what I see in gVim, fvim and nvim-qt.

I have 2 layouts, English and Russian.

I press Shift V to go to line visual mode.

gVim and nvim-qt behave the same way

## gvim / nvim-qt
normal mode, En active, S-V => Visual Line
normal mode, Ru active, S-V => nothing (blinks) since it's not mapped, but it can be overriden

## fvim
normal mode, En active or Ru active, S-V => Visual Line

I never had issues with that, because you don't need to have "native" layout ON in normal mode.

Now, when you are in Insert mode, you need to input something with your 2nd layout. As I said above, this is not possible in fvim as of now.

I used C-^ to switch between layouts in Vim for ages. I never touched system windows hotkeys for that.

But I recently found https://github.com/lyokha/vim-xkbswitch, which auto switches layouts if you use system hotkeys in insert mode. Please, take a look, but, again, it doesn't help you in `fvim`, only `nvim-qt` (or gVim).

**Comment by bybor** [comment]
@yatli , when I press `<c-v>` it enters visual block _for me_ but I'm not sure why. `<shift-v>` only "blinks". AFAIK normal mode requires EN layout, and I don't think I would like it the other way. I think that it may be possible to map your 2nd language into EN layout in normal mode, so that it works in normal mode with the 2nd layout. I think I saw it done for every key, but it feels very hacky to me. All the previous lines are about gVim.

I may be missing your point, but regarding `fvim`, it is really about supporting other layouts which it currently doesn't because of Avalonia that doesn't implement it. You just cannot type anything non-EN in insert mode.

I'm not very interested in testing some custom stuff, sorry. I want to rely on tools that I use and to have them available with the least effort possible. Custom builds somewhat don't fall into this category.

**Comment by krissen** [comment]
I'm all for testing stuff. :-)

Normal mode, visual mode -- it doesn't matter what layout your using. The point, as has been elaborated on before in this thread, is that regardless of the layout, said layout results in certain characters/input. That input has to be handled as it is entered. The default _keybindings_ in ViM are anglocentric, for sure; having such a layout makes the binds more easily accessible. But that's beside the point.

As @bybor said, and as been expressed earlier; this is an Avalonia bug. I don't see how you, @yatli, with any reasonable amount of effort can do anything about it. But lets see; I'll be happy to test what you've got.

**Comment by yatli** [comment]
@bybor thanks, that confirms my guess -- there's no control sequences at all for non ANSI characters, so control modified keys are sent as if they're on en-US.

**Comment by bybor** [comment]
@yatli , you probably know the things that are down the text, but I wanted to use correct Vim terms.

## langmap

Here is an example (for russian)

```
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz

```

The effect is that you can have Russian layout active and use normal mode, which for me means that `<c-v>` works too. You still have to switch system input language to be able to enter `: ` commands. The last point makes things weird and I use `keymap` instead.

I don't know if `fvim` supports `langmap`, but it doesn't make any difference from the viewpoint of the missing feature itself.

Thanks

**Comment by yatli** [comment]
@bybor after my modifications, langmap should work without problems -- let's see.

**Comment by yatli** [comment]
see: https://github.com/yatli/fvim/pull/202

I'm not going to merge it at the moment -- there may be stability issues.
Let the CI build the stuff and I'll put the link here.

**Comment by yatli** [comment]
CI build success.
Pick up your artifacts here: https://v-yadli.visualstudio.com/fvim/_build/results?buildId=650&view=artifacts&pathAsName=false&type=publishedArtifacts

![image](https://user-images.githubusercontent.com/20684720/135661360-dfa241f7-5c7a-492e-b986-cb917073a49c.png)

**Comment by yatli** [comment]
issue number one: `<` (shift-comma on enUS) is swallowed

**Comment by gibboni** [comment]
Same problem here now. For me `<` is a single key, no shift used. The same key with shift produces `>` and that works.  Also, now I can issue `:`without problems (shift-period). This was not possible before. I use a FI layout (on Linux).

**Comment by yatli** [comment]
fixed in 3014958

**Comment by yatli** [comment]
CI busy building stuff: https://v-yadli.visualstudio.com/fvim/_build/results?buildId=652&view=results
_insert deviantart wait animoji here_

**Comment by yatli** [comment]
@gibboni great news. It means the hack is working. :)

**Comment by gibboni** [comment]
Great work @yatli ! After the latest fix everything I've tested seem to work! :-)

**Comment by yatli** [comment]
:D

Latest artifacts here: https://v-yadli.visualstudio.com/fvim/_build/results?buildId=653&view=artifacts&pathAsName=false&type=publishedArtifacts

(Expires in 10 days)

**Comment by gibboni** [comment]
Well, it seems I forgot to test `~`. Sorry! This is produced by pressing `AltGr+^`. Now the `^`is swallowed and nothing comes out of it. Also the key with `´` is swallowed too.

**Comment by yatli** [comment]
@gibboni do you build yourself? If so, please try to run in debug mode and post some logs.
My guess is that `AltGr` is regarded as yet-another-alt (or the OS doesn't even send us the correct TextInput event)

**Comment by yatli** [comment]
Wow. `<AltGr-key>` with `FRA` layout is actually mapped to `<LeftCtrl-Alt-key>`
What is the numerical key for `^`?

**Comment by yatli** [comment]
In FRA `^` is `9` -- and `AltGr-9` puts `^9` into FVim

**Comment by gibboni** [comment]
Yes, I do build fvim myself. I got the following error when I pressed AltGr: `input: rejected: (Key (None, None), "")`

**Comment by gibboni** [comment]
Interesting. If I press the keys that got swallowed I got nothing. No errors.

**Comment by gibboni** [comment]
It seems that the AltGr is working even though log states "Key (None, None, ""). If I press AltGr-+ I get in the logs:
input: rejected: (Key (None, None), "")
input: rejected: (Key (None, OemPlus), "")
input: OnInput: key: "\"

The problem now seems to be, that some of the keys are completely dead and don't show anything in the log output.

**Comment by yatli** [comment]
@gibboni the internal logic is like this:

As mentioned earlier in the thread, for mapped keys, both KeyDown and TextInput events will be triggered.
I'm using some heuristic to determine whether a key is mapped, and reject the KeyDown event accordingly.
For some keys (e.g. AltGr+9), the KeyDown events are more complex than this -- FVim first receives Key(Ctrl), then Key(Ctrl+Alt, 9) -- and it cannot distinguish that from a enUS keyboard actually pressing Ctrl+Alt+9 -- so both the KeyDown and TextInput gets through.

**Comment by krissen** [comment]
> Latest artifacts here: https://v-yadli.visualstudio.com/fvim/_build/results?buildId=653&view=artifacts&pathAsName=false&type=publishedArtifacts

Tried going there to fetch it; I get to the page, click on `drop-osx` and then nothing happens. 🤷‍♂️ Attempted from a couple of browsers etc.

So thought I'd give building from source a go. `^HEAD` from `master` has the keyboard issue, ofc. But was built and worked as expected.

Checked out `^HEAD` (`d70d90a`) from branch `keyboard_layout`. Built successfully (`dotnet build -c Release`). Ran OK. But nothing happens regardless of what keys I press. The window just sits there. Tried building `3014958` but didn't make a difference.

Am new to dotnet, so perhaps I'm running the wrong commands or something? Or attempting to build the wrong branch? 

Let me know what I'm doing wrong -- or if the above means you've got testing results. ;-) Am on macOS, sv-SE.

**Comment by yatli** [comment]
@krissen https://v-yadli.visualstudio.com/862b0001-b236-4376-baf4-7c9655c99ba7/_apis/build/builds/653/artifacts?artifactName=drop-osx&api-version=6.0&%24format=zip

**Comment by krissen** [comment]
> @krissen https://v-yadli.visualstudio.com/862b0001-b236-4376-baf4-7c9655c99ba7/_apis/build/builds/653/artifacts?artifactName=drop-osx&api-version=6.0&%24format=zip

Got it. As with the version built from source, I get an unresponsive application window. That is it.

If I build it from source, it reads my vim dotfiles, and seems to have the appearance I'd expect etc. The "artifacts version" does not. (If I remove `.vim`, `.vimrc` and `.config/fvim` the FVim application window looks identical between built-from-source and artifacts.) But that's a different thing; the point to make in relation to the thread is that the application does not react to any input.

**Comment by yatli** [comment]
Thanks for testing.
This is probably OSX specific -- I remember Avalonia team talked about this.
So perhaps I'll have to dive into that issue myself... (again!)

**Comment by yatli** [comment]
@krissen did you try to run in debug mode? `dotnet run` directly.
What's the log like?

**Comment by krissen** [comment]
> @krissen did you try to run in debug mode? `dotnet run` directly. What's the log like?

I think the relevant parts would be the following:
```
input: rejected: (Key (None, I), "")
input: rejected: (Key (Shift, RightShift), "S")
input: rejected: (Key (None, U), "")
input: rejected: (Key (None, Q), "")
input: rejected: (Key (None, R), "")
input: rejected: (Key (None, D2), "")
input: rejected: (Key (None, D1), "")
input: rejected: (Key (None, W), "")
input: rejected: (Key (None, D3), "")
input: rejected: (Key (None, H), "")
input: rejected: (Key (None, G), "")
input: rejected: (Key (None, Space), "")
input: rejected: (Key (None, C), "")
input: rejected: (Key (None, H), "")
input: rejected: (Key (None, J), "")
input: rejected: (Key (None, D4), "")
input: rejected: (Key (None, G), "")
input: rejected: (Key (None, Space), "")
input: rejected: (Key (None, K), "")
input: rejected: (Key (None, J), "")
input: rejected: (Key (None, G), "")
input: rejected: (Key (None, D4), "")
input: rejected: (Key (None, Space), "")
```

That is, all input is rejected.

**Comment by krissen** [comment]
I could add, that it interprets keypresses according to an English keyboard layout.

That is, if I press `å`, `ä`, `ö`, respectively, it reads it as:
```
input: rejected: (Key (None, Oem4), "")
input: rejected: (Key (None, OemQuotes), "")
input: rejected: (Key (None, OemSemicolon), "")
```

**Comment by yatli** [comment]
Yeah, these are raw scancodes.
The `TextInput` events are missing. Game over for macOS. :(

**Comment by krissen** [comment]
Ah well. At least we played.

**Comment by yatli** [comment]
Next step attack vectors:

1. Avalonia, macOS, TextInput
2. Figure out better heuristic for AltGr translation

**Comment by yatli** [comment]
@krissen all hope is not lost!
When working on a input method-related bug I discovered a potential fix for macOS. Would you like to try it out?

The code is on merged to master, and the artifacts will be ready shortly.

**Comment by yatli** [comment]
This is the critical patch for macOS:

https://github.com/yatli/fvim/commit/9f975b626c155c1846cfb8e1e3252be0df5cd7ec

An Avalonia dev (thanks @maxkatz6 !) reminded me that in macOS, if a raw key is marked as "handled", it won't be translated to text input, which is confirmed by @krissen 's debug log.

**Comment by krissen** [comment]
Built it from master; so far, works like a charm! 🎉
<img width="477" alt="Skärmavbild 2022-03-12 kl  13 00 53" src="https://user-images.githubusercontent.com/2943684/158017173-48d34c9b-16fd-43b1-9c06-2fa5d57fd3b3.png">

Looking forward to trying it out some more!

**Comment by yatli** [comment]
Guys, v0.3.512 has been released with keyboard layout fix merged in.

**Comment by gibboni** [comment]
Hi! Was this fix meant only for macOS? Because on Windows nothing that requires AltGr still doesn't work.

**Comment by krissen** [comment]
(MacOS doesn't differentiate between Alt (or 'Opt' in Mac-speak) and AltGR, rather there is only (left-)Alt and (right-)Alt.)

**Comment by yatli** [comment]
v0.3.513 adds a new command `FVimKeyAltGr v:true` to enable aliasing.
I'm happily surprised to see it in action, that `7`, `shift-7`, `altgr-7` produces 3 different things :D

(not too surprised because some people here use this layout:
![image](https://user-images.githubusercontent.com/20684720/159091259-7e96b791-ac5d-49ab-bdc3-6bf5dd468a77.png)

**Comment by yatli** [comment]
0.3.513 is published. Case closed. 😎

**Comment by VVVFO** [comment]
@yatli  I'm using the Dvorak layout and experiencing issues with the latest build on macOS 12.3, if I press <C-h> in insert mode (raw key codes being Ctrl + J on QWERTY), FVim interprets it as <C-j> and inserts a newline instead of deleting one character back, same for all other shortcuts with Ctrl (e.g. <C-c> inserts a tab instead of exiting to normal mode). I tried with and without `FVimKeyAltGr v:true` without success.

Shift shortcuts appears to be fine though.

**Comment by yatli** [comment]
@VVVFO hey thanks for reporting. Yes I'm aware of this problem and I'm not sure how to solve this problem yet.

Let's open up a new thread for that.
https://github.com/yatli/fvim/issues/222
