### ISSUE TITLE
neovim rejects UI attachment with unrecognized options

### ISSUE THREAD

**Issue by cauer-feynsinn** [yatli/fvim#5]
First of all: Nice to see a neovim UI using a functional language (I am into Clojure :-) ) --- and a UI that doesn't use electron...

On Windows Version 10.0.17134 Build 17134 I get a blank screen when starting FVim
![grafik](https://user-images.githubusercontent.com/48285700/57674690-3f078800-7620-11e9-9184-0d20766e975d.png)

Neovim is 0.3.4 and init.vim is blank (for testing)

**Comment by yatli** [comment]
Hi!

Which version are you using? Currently master is wip and may be broken.

**Comment by cauer-feynsinn** [comment]
I am using the latest release 0.1.77

**Comment by yatli** [comment]
could you try to build a debug build? in release I disabled all the logs

**Comment by cauer-feynsinn** [comment]
I get the following exception when starting fvim from Visual Studio:

`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=FVim
  StackTrace:
   at FVim.EditorViewModel.get_BufferWidth() in ...\fvim\ViewModels\EditorViewModel.fs:line 521`

The log is:

`'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\Documents\workspace\fvim\bin\Debug\netcoreapp2.1\FVim.dll'. Symbols loaded.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Console.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.DesktopRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Controls.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Styling.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Input.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Interactivity.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Layout.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Visuals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Animation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Base.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.ObjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Collections.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.ComponentModel.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Threading.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia.win32\0.8.0\lib\netstandard2.0\Avalonia.Win32.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia.native\0.8.0\lib\netstandard2.0\Avalonia.Native.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia.x11\0.8.0\lib\netstandard2.0\Avalonia.X11.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia.desktop\0.8.0\lib\netstandard2.0\Avalonia.Desktop.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia.reactiveui\0.8.0\lib\netstandard2.0\Avalonia.ReactiveUI.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Logging.Serilog.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia.skia\0.8.0\lib\netstandard2.0\Avalonia.Skia.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Runtime.InteropServices.RuntimeInformation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\serilog\2.5.0\lib\netstandard1.3\Serilog.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\serilog.sinks.debug\1.0.0\lib\netstandard1.0\Serilog.Sinks.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Runtime.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Globalization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Xml.XDocument.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Private.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Private.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Runtime.InteropServices.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Memory.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.OpenGL.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\skiasharp\1.68.0\lib\netstandard1.3\SkiaSharp.dll'. Cannot find or open the PDB file.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\system.reactive\4.0.0\lib\netstandard2.0\System.Reactive.dll'. 
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.ComponentModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Threading.Timer.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Markup.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Markup.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\fsharp.core\4.6.2\lib\netstandard1.6\FSharp.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Resources.ResourceManager.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.ComponentModel.TypeConverter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Collections.Specialized.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Drawing.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Collections.Concurrent.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Themes.Default.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Reflection.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.IO.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."Y"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."Y"' is not registered on '"Avalonia.Controls.Border"'.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Threading.Tasks.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\reactiveui\9.0.1\lib\netcoreapp2.0\ReactiveUI.dll'. 
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\splat\4.0.2\lib\netstandard2.0\Splat.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\fsharp.data\3.1.1\lib\netstandard2.0\FSharp.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\taskbuilder.fs\2.1.0\lib\netstandard1.6\TaskBuilder.fs.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Diagnostics.TraceSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Reflection.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
FVim Information: 0 : Model: starting neovim instance...
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Diagnostics.Process.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\fsharp.control.reactive\4.2.0\lib\netstandard2.0\FSharp.Control.Reactive.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder\messagepack\1.7.3.4\lib\netstandard2.0\MessagePack.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
FVim Information: 0 : neovim: READ!
FVim Information: 0 : Model: registering rpc handlers
FVim Information: 0 : Model: commencing early initialization...
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Reflection.Emit.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'MessagePack.Resolvers.DynamicEnumResolver'. 
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Reflection.Emit.ILGeneration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Reflection.Emit.Lightweight.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Reflection.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'MessagePack.Resolvers.DynamicUnionResolver'. 
'dotnet.exe' (CoreCLR: clrhost): Loaded 'MessagePack.Resolvers.DynamicObjectResolver'. 
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Threading.Tasks.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
FVim Information: 0 : neovim: call: [0,0,"nvim_set_var",["fvim_loaded",1]]
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.IO.FileSystem.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Text.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
FVim Information: 0 : fontConfig: guifont=Iosevka Slab guifontwide=DengXian size=4.3984375, 21.28125
FVim Information: 0 : Model: attaching to nvim on first grid ready signal. size = 22 4
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.1.7\System.Runtime.Serialization.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
FVim Information: 0 : neovim: call: [0,1,"nvim_ui_attach",[22,4,{"rgb":true,"ext_popupmenu":false,"ext_tabline":false,"ext_cmdline":false,"ext_wildmenu":false,"ext_messages":false,"ext_linegrid":true,"ext_multigrid":true,"ext_hlstate":false,"ext_termcolors":false}]]
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\avalonia\0.8.0\lib\netcoreapp2.0\Avalonia.Diagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded '...\.nuget\packages\system.drawing.common\4.5.0\runtimes\win\lib\netcoreapp2.0\System.Drawing.Common.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
FVim Information: 0 : cursor: render tick 0
FVim Information: 0 : editor: render tick 0
Exception thrown: 'System.NullReferenceException' in FVim.dll
**grid_fb** was null.
`

**Comment by yatli** [comment]
Switch to the release branch and try again.
master is wip

**Comment by cauer-feynsinn** [comment]
The same happens with the release branch :-/

**Comment by yatli** [comment]
I notice `"ext_multigrid":true` -- is this on release branch? :O

**Comment by yatli** [comment]
could you please provide the output in a `release branch` run?
I cannot repro your problem, but I can add some guards anyway

**Comment by yatli** [comment]
are there errors in your vimrc?

**Comment by cauer-feynsinn** [comment]
This is the output on the release branch (I cleaned the project before compilation just to be sure):

`Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."Y"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."Y"' is not registered on '"Avalonia.Controls.Border"'.
FVim Information: 0 : Model: starting neovim instance...
FVim Information: 0 : neovim: READ!
FVim Information: 0 : Model: registering rpc handlers
FVim Information: 0 : Model: commencing early initialization...
FVim Information: 0 : neovim: call: [0,0,"nvim_set_var",["fvim_loaded",1]]
FVim Information: 0 : fontConfig: guifont=Iosevka Slab guifontwide=DengXian size=4.3984375, 21.28125
FVim Information: 0 : Model: attaching to nvim on first grid ready signal. size = 22 4
FVim Information: 0 : neovim: call: [0,1,"nvim_ui_attach",[22,4,{"rgb":true,"ext_popupmenu":false,"ext_tabline":false,"ext_cmdline":false,"ext_wildmenu":false,"ext_messages":false,"ext_linegrid":true,"ext_multigrid":true,"ext_hlstate":false,"ext_termcolors":false}]]
FVim Information: 0 : cursor: render tick 0
FVim Information: 0 : editor: render tick 0
Exception thrown: 'System.NullReferenceException' in FVim.dll
**grid_fb** was null.`

For testing purposes, I've removed my init.vim and the error is the same.

**Comment by cauer-feynsinn** [comment]
BTW this is what SourceTree says: 
![grafik](https://user-images.githubusercontent.com/48285700/57695593-f4e9cb00-764e-11e9-9ed5-1b00566d236c.png)

**Comment by cauer-feynsinn** [comment]
Upps, sorry, I was using a local release branch. Hiere is the output when using origin/release:
`Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."X"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."Y"' is not registered on '"Avalonia.Controls.Border"'.
Property: Property '"Avalonia.Media.TranslateTransform"."Y"' is not registered on '"Avalonia.Controls.Border"'.
FVim Information: 0 : Model: starting neovim instance...
FVim Information: 0 : neovim: READ!
FVim Information: 0 : Model: registering rpc handlers
FVim Information: 0 : Model: commencing early initialization...
FVim Information: 0 : neovim: call: [0,0,"nvim_set_var",["fvim_loaded",1]]
FVim Information: 0 : fontConfig: guifont=Iosevka Slab guifontwide=DengXian size=4.3984375, 21.28125
FVim Information: 0 : Model: attaching to nvim on first grid ready signal. size = 22 4
FVim Information: 0 : neovim: call: [0,1,"nvim_ui_attach",[22,4,{"rgb":true,"ext_popupmenu":false,"ext_tabline":false,"ext_cmdline":false,"ext_wildmenu":false,"ext_messages":false,"ext_linegrid":true,"ext_multigrid":false,"ext_hlstate":false,"ext_termcolors":false}]]
FVim Information: 0 : cursor: render tick 0
FVim Information: 0 : editor: render tick 0
Exception thrown: 'System.NullReferenceException' in FVim.dll
**grid_fb** was null`
Same error though but with ext_multigrid:false

**Comment by yatli** [comment]
looks like you've sent the ui attach request but there's no response from neovim. why?

**Comment by yatli** [comment]
Hmm, I’ll look into the exception

**Comment by cauer-feynsinn** [comment]
nvim.exe is in my PATH. Do I have to specifiy the path to NVIM somewhere else?

**Comment by yatli** [comment]
Nope, nvim is launched successfully according to the log.

**Comment by pulcinello** [comment]
Same issue here. Fvim worked well with release 0.1.72 but got blank screen with 0.1.77.

**Comment by yatli** [comment]
@pulcinello  @cauer-feynsinn  I'm also observing some rendering problems -- render ticks are not firing, so the view is not updated promptly.

Pushed out a new version that fixes the bindings (0.1.83). Could you test it out?

**Comment by cauer-feynsinn** [comment]
I've still got the same behavior (blank screen) though this time nvim seems to receive events:
`FVim Information: 0 : editorvm #1: set measured size: 1424, 810
FVim Information: 0 : editorvm #1: set measured size: 800, 600
FVim Information: 0 : Model: Grid #1 resized to 181 28
FVim Information: 0 : neovim: call: [0,2,"nvim_ui_try_resize",[181,28]]
FVim Information: 0 : neovim: call: [0,3,"nvim_command",["runtime! ginit.vim"]]
FVim Information: 0 : Model: OnInput: Key (None,I)
FVim Information: 0 : neovim: call: [0,4,"nvim_input",["i"]]
FVim Information: 0 : Model: OnInput: TextInput "i"
FVim Information: 0 : input: rejected: TextInput "i"
The thread 0x7efc has exited with code 0 (0x0).
The thread 0x82a0 has exited with code 0 (0x0).
The thread 0x677c has exited with code 0 (0x0).
The thread 0x6328 has exited with code 0 (0x0).
The thread 0x54f8 has exited with code 0 (0x0).
The thread 0x5da0 has exited with code 0 (0x0).
The thread 0x7280 has exited with code 0 (0x0).
FVim Information: 0 : Model: OnInput: Key (None,J)
FVim Information: 0 : neovim: call: [0,5,"nvim_input",["j"]]
FVim Information: 0 : Model: OnInput: TextInput "j"
FVim Information: 0 : input: rejected: TextInput "j"
FVim Information: 0 : Model: OnInput: Key (None,K)
FVim Information: 0 : neovim: call: [0,6,"nvim_input",["k"]]
FVim Information: 0 : Model: OnInput: TextInput "k"
FVim Information: 0 : input: rejected: TextInput "k"
FVim Information: 0 : Model: OnInput: Key (None,L)
FVim Information: 0 : neovim: call: [0,7,"nvim_input",["l"]]
FVim Information: 0 : Model: OnInput: TextInput "l"
FVim Information: 0 : input: rejected: TextInput "l"
FVim Information: 0 : Model: OnInput: Key (None,A)
FVim Information: 0 : neovim: call: [0,8,"nvim_input",["a"]]
FVim Information: 0 : Model: OnInput: TextInput "a"
FVim Information: 0 : input: rejected: TextInput "a"
FVim Information: 0 : Model: OnInput: Key (None,S)
FVim Information: 0 : neovim: call: [0,9,"nvim_input",["s"]]
FVim Information: 0 : Model: OnInput: TextInput "s"
FVim Information: 0 : input: rejected: TextInput "s"
FVim Information: 0 : Model: OnInput: Key (None,D)
FVim Information: 0 : neovim: call: [0,10,"nvim_input",["d"]]
FVim Information: 0 : Model: OnInput: TextInput "d"
FVim Information: 0 : input: rejected: TextInput "d"
FVim Information: 0 : Model: OnInput: Key (None,F)
FVim Information: 0 : neovim: call: [0,11,"nvim_input",["f"]]
FVim Information: 0 : Model: OnInput: TextInput "f"
FVim Information: 0 : input: rejected: TextInput "f"
FVim Information: 0 : Model: OnInput: MousePress (LeftMouseButton,8,174,Left,1)
FVim Information: 0 : neovim: call: [0,12,"nvim_input",["<LeftMouse><174,8>"]]
FVim Information: 0 : Model: OnInput: MouseRelease (None,8,174,Left)
FVim Information: 0 : neovim: call: [0,13,"nvim_input",["<LeftRelease><174,8>"]]`

The NullReferenceException does not occur.

**Comment by yatli** [comment]
@cauer-feynsinn I still don't see render ticks in your log.

**Comment by yatli** [comment]
I think this needs to be reopened. I'm seeing this on WSL also.

**Comment by yatli** [comment]
@cauer-feynsinn @pulcinello root cause resolved.

The neovim rejected our request to attach UI.
Reason: fvim is sending UI options from 0.4.x, not understood by 0.3.x neovim.

disabling the related options works around the problem.

**Comment by yatli** [comment]
log captured in WSL:

![image](https://user-images.githubusercontent.com/20684720/57903409-74baa400-78a0-11e9-9dd2-c39b4084618c.png)

**Comment by yatli** [comment]
`0.1.98` should fix the problem. @cauer-feynsinn  @pulcinello could you please test it out?

**Comment by pulcinello** [comment]
Just tried 0.1.98 and 0.1.101 on my computer(Win10 with nvim 0.3.5 ). Still no luck. I believe this issue is related to neovim's version like you said 'cause on my another computer(Ubuntu 18.04 with nvim 0.4) fvim works really fine.

**Comment by yatli** [comment]
I'm trying `0.3.5` from `chocolatey`.

**Comment by pulcinello** [comment]
It works!:ok_hand: Thanks for your hard work!:thumbsup:

**Comment by yatli** [comment]
Closing this issue now; Feel free to reopen if you still have problems.
